/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/me/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Endpoints for the currently authenticated user. */
        get: operations["me_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me/profile/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Endpoints for the currently authenticated user. */
        patch: operations["me_profile_partial_update"];
        trace?: never;
    };
    "/api/recipes/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipes_list"];
        put?: never;
        post: operations["recipes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{slug}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["recipes_retrieve"];
        put: operations["recipes_update"];
        post?: never;
        delete: operations["recipes_destroy"];
        options?: never;
        head?: never;
        patch: operations["recipes_partial_update"];
        trace?: never;
    };
    "/api/users/{username}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Public user profiles. */
        get: operations["users_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {unknown} */
        BlankEnum: "";
        PaginatedRecipeListList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["RecipeList"][];
        };
        /** @description Input DTO for create/update — nested ingredients on write. */
        PatchedRecipeWrite: {
            title?: string;
            instructions?: string;
            program?: components["schemas"]["ProgramEnum"] | components["schemas"]["BlankEnum"];
            ingredients?: components["schemas"]["RecipeIngredientWrite"][];
            tag_slugs?: string[];
            is_published?: boolean;
        };
        /** @description Current authenticated user — used by the FE for global session context. */
        PatchedUserMe: {
            readonly id?: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username?: string;
            /**
             * Email address
             * Format: email
             */
            readonly email?: string;
            bio?: string;
            /** Format: uri */
            avatar?: string | null;
        };
        /**
         * @description * `ice_cream` - Ice Cream
         *     * `lite_ice_cream` - Lite Ice Cream
         *     * `sorbet` - Sorbet
         *     * `gelato` - Gelato
         *     * `smoothie_bowl` - Smoothie Bowl
         *     * `milkshake` - Milkshake
         *     * `mix_in` - Mix-in
         *     * `frozen_yogurt` - Frozen Yogurt
         *     * `italian_ice` - Italian Ice
         * @enum {string}
         */
        ProgramEnum: "ice_cream" | "lite_ice_cream" | "sorbet" | "gelato" | "smoothie_bowl" | "milkshake" | "mix_in" | "frozen_yogurt" | "italian_ice";
        /** @description Full DTO for the recipe detail page. */
        RecipeDetail: {
            readonly id: number;
            readonly title: string;
            readonly slug: string;
            readonly created_by: components["schemas"]["UserPublic"];
            readonly program: components["schemas"]["ProgramEnum"];
            readonly program_display: string;
            readonly tags: components["schemas"]["Tag"][];
            /** Format: date-time */
            readonly created_at: string;
            instructions: string;
            readonly ingredients: components["schemas"]["RecipeIngredient"][];
            readonly images: components["schemas"]["RecipeImage"][];
            is_published?: boolean;
            /** Format: date-time */
            readonly updated_at: string;
        };
        RecipeImage: {
            readonly id: number;
            /** Format: uri */
            image: string;
            sort_order?: number;
        };
        RecipeIngredient: {
            readonly id: number;
            section?: components["schemas"]["SectionEnum"];
            name: string;
            /** Format: decimal */
            quantity?: string | null;
            unit?: string;
            prep_note?: string;
            sort_order?: number;
        };
        RecipeIngredientWrite: {
            section?: components["schemas"]["SectionEnum"];
            name: string;
            /** Format: decimal */
            quantity?: string | null;
            unit?: string;
            prep_note?: string;
            sort_order?: number;
        };
        /** @description Lightweight DTO for feeds and search results. */
        RecipeList: {
            readonly id: number;
            readonly title: string;
            readonly slug: string;
            readonly created_by: components["schemas"]["UserPublic"];
            readonly program: components["schemas"]["ProgramEnum"];
            readonly program_display: string;
            readonly tags: components["schemas"]["Tag"][];
            /** Format: date-time */
            readonly created_at: string;
        };
        /** @description Input DTO for create/update — nested ingredients on write. */
        RecipeWrite: {
            title: string;
            instructions: string;
            program?: components["schemas"]["ProgramEnum"] | components["schemas"]["BlankEnum"];
            ingredients: components["schemas"]["RecipeIngredientWrite"][];
            tag_slugs?: string[];
            is_published?: boolean;
        };
        /**
         * @description * `base` - Base
         *     * `mix_in` - Mix-in
         * @enum {string}
         */
        SectionEnum: "base" | "mix_in";
        Tag: {
            readonly slug: string;
            readonly label: string;
        };
        /** @description Current authenticated user — used by the FE for global session context. */
        UserMe: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username: string;
            /**
             * Email address
             * Format: email
             */
            readonly email: string;
            bio?: string;
            /** Format: uri */
            avatar?: string | null;
        };
        /** @description Read-only public profile shown on recipe cards and author pages. */
        UserPublic: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            readonly username: string;
            readonly bio: string;
            /** Format: uri */
            readonly avatar: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"][];
                };
            };
        };
    };
    me_profile_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserMe"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserMe"];
                "multipart/form-data": components["schemas"]["PatchedUserMe"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserMe"];
                };
            };
        };
    };
    recipes_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRecipeListList"];
                };
            };
        };
    };
    recipes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["RecipeWrite"];
                "multipart/form-data": components["schemas"]["RecipeWrite"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeWrite"];
                };
            };
        };
    };
    recipes_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeDetail"];
                };
            };
        };
    };
    recipes_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["RecipeWrite"];
                "multipart/form-data": components["schemas"]["RecipeWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeWrite"];
                };
            };
        };
    };
    recipes_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recipes_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRecipeWrite"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRecipeWrite"];
                "multipart/form-data": components["schemas"]["PatchedRecipeWrite"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeWrite"];
                };
            };
        };
    };
    users_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
        };
    };
}
